version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: shop-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - app

  auth-shop:
    build: ./backend-auth
    container_name: auth-shop
    ports:
      - "8081:8081"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8081
      - APP_ENV=local
      - PATH_PRIVATE_KEY=/app/keys/private.pem
      - PATH_PUBLIC_KEY=/app/keys/public.pem
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=postgres
      - SENDER_HOST=auth-shop:8081
    volumes:
      - ./backend/auth/keys:/app/keys
    depends_on:
      - postgres
    networks:
      - app

  shop:
    build: ./backend-shop
    container_name: shop
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - APP_ENV=local
      - PATH_PUBLIC_KEY=/app/keys/public.pem
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB_NAME=postgres
    volumes:
      - ./backend/shop/keys:/app/keys
    depends_on:
      - postgres
    networks:
      - app

  frontend:
    build: ./frontend
    volumes:
      - frontend-build:/dist

  nginx:
    image: nginx:stable
    ports:
      - "8088:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend-build:/usr/share/nginx/html
    depends_on:
      - frontend
    networks:
      - app

volumes:
  pgdata:
  frontend-build:

networks:
  app:
    driver: bridge
