services:
  postgres:
    image: postgres:latest
    container_name: shop-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:latest
    container_name: shop-redis
    networks:
      - app
    volumes:
      - redis-data:/data



volumes:
  redis-data:
    driver: local
  pgdata:
    driver: local

networks:
  app:
    driver: bridge

